### ISSUE TITLE
Fejl v. opdatering

### ISSUE THREAD

**Issue by styrke10** [mapcentia/DAWAreplicator#2]
Hej Martin,

Nu fungerer initiering og første download af data som en drøm, men til gengæld får jeg en fejl på adgangsadresser, når jeg kører en opdatering. Fejlen er følgende:
------------------------------------------
C:\>java -jar DAWAreplicator.jar config.yml
Connecting to database: jdbc:postgresql://192.168.1.165:5432/DAR

2017-06-19T05:50:24.219Z
Database : 3252541
Seneste  : 3252831

http://dawa.aws.dk/replikering/postnumre/haendelser?sekvensnummerfra=3252541&sekvensnummertil=3252831

http://dawa.aws.dk/replikering/ejerlav/haendelser?sekvensnummerfra=3252541&sekvensnummertil=3252831

http://dawa.aws.dk/replikering/vejstykker/haendelser?sekvensnummerfra=3252542&sekvensnummertil=3252831

http://dawa.aws.dk/replikering/AdgangsAdresser/haendelser?sekvensnummerfra=3252542&sekvensnummertil=3252831
Exception in thread "main" java.lang.NullPointerException
        at com.mapcentia.aws_sync.AdgangsAdresserEvent.get(AdgangsAdresserEvent.java:123)
        at com.mapcentia.aws_sync.ReplicaEvent.start(ReplicaEvent.java:71)
        at com.mapcentia.aws_sync.Main.main(Main.java:30)
--------------------------------------------

Jeg kan ikke lige gennemskue, hvad der eventuelt går galt?

**Comment by mapcentia** [comment]
Hej Morten,
Det ser ud til, at værdien "ændret" er ikke er sat i mindst et af update JSON objekterne i sekvensen (der er 16). Java koden tjekker ikke for NULL på dette felt, da det altid skal være udfyldt. Men det er de umiddelbart også: http://dawa.aws.dk/replikering/AdgangsAdresser/haendelser?sekvensnummerfra=3252542&sekvensnummertil=3252831

Kan du prøve at køre igen - det kan være, at det var en manglende værdi, som nu er udfyldt. Ellers sætter jeg en test op med den sekvens.

**Comment by styrke10** [comment]
Hej igen,
Har prøvet at køre igen - nu med ny sekvensnummertil - men resultatet er det samme:
C:\>java -jar DAWAreplicator.jar config.yml
Connecting to database: jdbc:postgresql://192.168.1.165:5432/DAR

2017-06-19T07:18:24.956Z
Database : 3252541
Seneste  : 3253521

http://dawa.aws.dk/replikering/postnumre/haendelser?sekvensnummerfra=3252541&sekvensnummertil=3253521

http://dawa.aws.dk/replikering/ejerlav/haendelser?sekvensnummerfra=3252541&sekvensnummertil=3253521

http://dawa.aws.dk/replikering/vejstykker/haendelser?sekvensnummerfra=3252542&sekvensnummertil=3253521

http://dawa.aws.dk/replikering/AdgangsAdresser/haendelser?sekvensnummerfra=3252542&sekvensnummertil=3253521
Exception in thread "main" java.lang.NullPointerException
        at com.mapcentia.aws_sync.AdgangsAdresserEvent.get(AdgangsAdresserEvent.java:123)
        at com.mapcentia.aws_sync.ReplicaEvent.start(ReplicaEvent.java:71)
        at com.mapcentia.aws_sync.Main.main(Main.java:30)

**Comment by mapcentia** [comment]
Hvilken encoding har din database?

**Comment by styrke10** [comment]
UTF8

**Tilføjelse:** Kiggede lige lidt nærmere på tingene og kan se, at jeg har problemer med æøå...!! Kan der være en sammenhæng?

**Comment by mapcentia** [comment]
Ja, jeg mistænker, at det er et encoding problem. DAWA folkene har nemlig været så letsindige at bruge danske bogstaver i JSON property navnene og derfor bruges de også i Java class'en (hvilket ikke er så hensigtsmæssig). Jeg kan ikke genskabe fejlen, men har nu explicit sat, at det er UTF8 encoded JSON, der bliver hentet. Jeg opdagede samtidig en fejl i INIT metoderne, som gør, at der kan ske overlap mellem id'er efter den første INIT. Rettelserne er pushed. Så en god ide er, at slette alle tabeller og køre init igen. Du kan også prøve at køre java med: java -Dfile.encoding=UTF-8 -jar .....

**Comment by styrke10** [comment]
Smukt - så ser alt ud til at virke! Inkl. korrekte danske karakterer i sted- og vejnavne! På trods af DAWAs lemfældige omgang med æøå i properties etc... :-)
